### ISSUE TITLE
onprem install do not use  curl to https://www.uuidtools.com/api/generate/timestamp-first

### ISSUE THREAD

**Issue by orellabac** [TeamCodeStream/onprem-install#2]
Currently this make this script to fail sometimes because https://www.uuidtools.com/api/generate/timestamp-first is using cloudfare protection and that will break the curl result. 

sudo apt-get install uuid-runtime could be used for example

**Comment by jimmyjayp** [comment]
Hi orellabac, thanks for reporting the issue.  I looked at your PR but due to our requirement that the codestream control script support the broadest number of distributions possible, I'm not comfortable making the script assume you've installed that particular uuid generator package.

If you'd like, I can make a change that would attempt to use a locally installed uuid generator as a higher priority than going out over the web, while keeping the web as a last-resort option. Let me know.

**Comment by orellabac** [comment]
ok. that sounds good. I think that in general using uuidtools.com is no
longer an option due to the cloudfare.com redirection. But as long as there
is an option to opt out of the web option that would be fine.

Thank you

**Comment by jimmyjayp** [comment]
Committed the enhancement on the next branch which should be released in a few days.  https://github.com/TeamCodeStream/onprem-install/commit/335bc80e010e18868417fe7b8d7a6f2fa199352f .  I'm closing the PR as well.
